### PR TITLE
add bypasses for downloadr.in, theepochtimes,animestc.xyz & apkdone.com

### PR DESCRIPTION
**Pull request by lem6ns**
(sorry for shitty code & also sorry if I placed the code not at the right insertion point!!! been so long)

### CODE REVIEW

**Comment by marcussacana** [comment]
Sorry, I recommended this fork but looks like he isn't really maintening... 
Do you know about any fork continuing the tool?

**Comment by lem6ns** [comment]
> 
> 
> Sorry, I recommended this fork but looks like he isn't really maintening...
> Do you know about any fork continuing the tool?

No, not really

**Comment by NotAProton** [comment]
@respecting @marcussacana 
https://github.com/FastForwardTeam/FastForward 
we are maintaining

**Comment by marcussacana** [comment]
@NotAProton God Job, thanks.

**Comment by lem6ns** [comment]
👍

**Pull request closed without merging**
